### PR TITLE
Adding 24px icons

### PR DESCRIPTION
**Pull request by stnrd**
[WIP] - Adding support for 24px icons

### CODE REVIEW

**Review by hetmann — APPROVED** [review]

**Comment by hetmann** [comment]
@stnrd you can create a DRAFT PR :)

**Comment by stnrd** [comment]
I still need to do some work on this PR. At the moment the newly 24px icons are ignored in the build process. I am not sure yet how to expose them in the resulting npm package yet. Any ideas?

**Comment by hetmann** [comment]
> I still need to do some work on this PR. At the moment the newly 24px icons are ignored in the build process. I am not sure yet how to expose them in the resulting npm package yet. Any ideas?

### 1st idea
- create new variants at : https://github.com/stnrd/healthicons/blob/9161da0a6cc7c513b12353ab7c68a7df62e4d460/bin/build/index.js#L13
```js
const iconsVariants = ["filled", "outline", "filled-24px", "outline-24px"];
```
But this will create new folders with all 48px icons and ONLY with 24px icons:
| DIR | 24px | 48px |
| --- | --- | --- |
| image | image | image | 

### 2nd idea
- find the 24px icon and create `icon-name-24px` file icon, e.g.:  `Body.js` and `Body24px.js`

**Comment by stnrd** [comment]
Thanks for you input - I was thinking of the first idea as well. Doing the second one is quite a change in the build process and the first one is only adding the new 24px variants and exposing them with he packages package.json. I am implementing it now.

**Review by hetmann — APPROVED** [review]

**Pull request merged**
